name: Ubuntu TON build (shared, x86-64)

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04-arm64, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:      
        submodules: 'recursive'

    - name: Install system libraries
      run: |
        git clone --recursive https://github.com/ton-blockchain/ton.git ton

    - if: matrix.os != 'ubuntu-24.04'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16 all

    - name: Build TON
      run: |
        cd ton
        cp assembly/native/build-ubuntu-shared.sh .
        chmod +x build-ubuntu-shared.sh
        ./build-ubuntu-shared.sh -t -a

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries-${{ matrix.os }}
        path: ton/artifacts
