name: Build all (master,release)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

  ton-linux-arm64:
    needs: [build]
    uses: ./.github/workflows/ton-linux-arm64.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}

  ton-linux-x86-64:
    needs: [build]
    uses: ./.github/workflows/ton-linux-x86-64.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}

  ton-macos-arm64:
    needs: [build]
    uses: ./.github/workflows/ton-macos-arm64.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}

  ton-macos-x86-64:
    needs: [build]
    uses: ./.github/workflows/ton-macos-x86-64.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}

  ton-windows-x86-64:
    needs: [build]
    uses: ./.github/workflows/ton-windows-x86-64.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}