name: Monitor (native,master)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      res: ${{ steps.res.outputs.res }}
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - name: If triggered manually we are ok
        run: |
          echo "res=0" >> $GITHUB_OUTPUT

      - name: Check if there was an update
        id: res
        if: ${{ github.event_name == 'schedule' }}
        run: |
          RESULT=$(curl -s https://api.github.com/repos/ton-blockchain/ton/commits/master | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*30) | trunc)")
          echo $RESULT
          echo "res=$RESULT" >> $GITHUB_OUTPUT

  ton-all-native-master:
    if: needs.build.outputs.res == 0
    needs: [build]
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    uses: ./.github/workflows/build-all-native-master.yml
    with:
      branch: master

  add-master-to-release:
    needs: [ton-all-native-master]
    uses: ./.github/workflows/add-master-to-release-native.yml
    with:
      branch: master