name: Monitor (shared,master)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      res: ${{ steps.res.outputs.res }}
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - name: Check if there was an update
        id: res
        run: |
          RESULT=$(curl -s https://api.github.com/repos/ton-blockchain/ton/commits/master | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*30) | trunc)")
          echo $RESULT
          echo "res=$RESULT" >> $GITHUB_OUTPUT

  ton-all-shared-master:
    if: needs.build.outputs.res == 0
    needs: [build]
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    uses: ./.github/workflows/build-all-shared-master.yml
    with:
      branch: master