name: Release all (nix, master)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out current repository
        uses: actions/checkout@v4        

  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-all-nix-master.yml
          path: artifacts
          workflow_conclusion: success
          skip_unpack: true

      # create release
      - name: Get next tag
        id: tag
        run: |
          ls -lart
          echo ---------------------
          ls -lart artifacts
          git fetch --all --tags
          git tag -l
          NEW_TAG=v$(date +'%Y.%m')
          FOUND=$(git tag -l | grep $NEW_TAG | wc -l)
          if [ $FOUND -eq 0 ]; then
            echo "TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          else
            echo "TAG=$NEW_TAG-$FOUND" >> $GITHUB_OUTPUT
          fi

      - name: Get registration token
        id: getRegToken
        run: |
          curl -X POST -H \"Accept: application/vnd.github+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/ton-blockchain/ton/actions/runners/registration-token

      - uses: sgpublic/delete-release-action@v1.1
        with:
          # repo: '<owner>/<repoName>' # you can input a another repo here, defaults to current repo
          release-drop: true
          release-keep-count: -1
          release-drop-tag: true
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: -1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          release_name: TON ${{ steps.tag.outputs.TAG }}
          draft: false
          prerelease: false


      # upload artifacts to release
      - name: Upload Linux x86-64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-linux-x86-64-${{ inputs.branch }}
          asset_name: ton-linux-x86-64.zip
          tag: ${{ steps.tag.outputs.TAG }}

      - name: Upload Linux arm64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-linux-arm64-${{ inputs.branch }}
          asset_name: ton-linux-arm64.zip
          tag: ${{ steps.tag.outputs.TAG }}

      - name: Upload MacOS x86-64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-mac-x86-64-${{ inputs.branch }}
          asset_name: ton-mac-x86-64.zip
          tag: ${{ steps.tag.outputs.TAG }}

      - name: Upload MacOS arm64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-mac-arm64-${{ inputs.branch }}
          asset_name: ton-mac-arm64.zip
          tag: ${{ steps.tag.outputs.TAG }}

      - name: Upload Windows x86-64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-win-x86-64-${{ inputs.branch }}
          asset_name: ton-win-x86-64.zip
          tag: ${{ steps.tag.outputs.TAG }}