name: Release all (nix, master)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out current repository
        uses: actions/checkout@v4        

  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-all-nix-master.yml
          path: artifacts
          workflow_conclusion: success
          skip_unpack: true

      # create release
      - name: Get next tag
        id: tag
        run: |
          NEW_TAG=v$(date +'%Y.%m')
          echo "TAG=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Get registration token
        id: getRegToken
        run: |
          curl -X POST -H \"Accept: application/vnd.github+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/neodix42/ton-actions/actions/runners/registration-token

      - uses: ClementTsang/delete-tag-and-release@v0.3.1
        with:
          delete_release: true
          tag_name: ${{ steps.tag.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          release_name: TON ${{ steps.tag.outputs.TAG }}
          draft: false
          prerelease: false


      # upload artifacts to release
      - name: Upload Linux x86-64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-linux-x86-64-${{ inputs.branch }}.zip
          asset_name: ton-linux-x86-64-${{ inputs.branch }}.zip
          tag: ${{ steps.tag.outputs.TAG }}

      - name: Upload Linux arm64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-linux-arm64-${{ inputs.branch }}.zip
          asset_name: ton-linux-arm64-${{ inputs.branch }}.zip
          tag: ${{ steps.tag.outputs.TAG }}

      - name: Upload MacOS x86-64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-mac-x86-64-${{ inputs.branch }}.zip
          asset_name: ton-mac-x86-64-${{ inputs.branch }}.zip
          tag: ${{ steps.tag.outputs.TAG }}

      - name: Upload MacOS arm64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-mac-arm64-${{ inputs.branch }}.zip
          asset_name: ton-mac-arm64-${{ inputs.branch }}.zip
          tag: ${{ steps.tag.outputs.TAG }}

      - name: Upload Windows x86-64 artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/ton-win-x86-64-${{ inputs.branch }}.zip
          asset_name: ton-win-x86-64-${{ inputs.branch }}.zip
          tag: ${{ steps.tag.outputs.TAG }}