name: Test

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - name: Check if there was an update
        id: check
        run: |
          RES=$(curl -s https://api.github.com/repos/ton-blockchain/ton/commits/master | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*60*48) | trunc)")
          echo $RES          
          exit $RES

  ton-all-shared-master:
    if: always() && (needs.build.result == 'success')
    needs: [build]
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    uses: ./.github/workflows/build-all-shared-master.yml
    with:
      branch: master