name: U-22.04-arm64 (nix)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

jobs:
  build:
    runs-on: [self-hosted, ubuntu-22.04-arm64]
    env:
      WORK_DIR: ${{ github.run_id }}-${{ github.run_attempt }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: ./${{ env.WORK_DIR }}

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Clone TON
      working-directory: ${{ env.WORK_DIR }}
      run: |
        git clone --recursive https://github.com/ton-blockchain/ton.git ton
        cd ton; git checkout ${{ inputs.branch }}; git submodule sync --recursive; git submodule update

    - name: Build TON
      working-directory: ${{ env.WORK_DIR }}
      run: |
        cd ton
        cp assembly/nix/build-linux-arm64-nix.sh .
        chmod +x build-linux-arm64-nix.sh
        ./build-linux-arm64-nix.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-linux-arm64-${{ inputs.branch }}
        path: ${{ env.WORK_DIR }}/ton/artifacts
