name: U-22.04-x86-64 (nix)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - run: |
        sudo apt update
        sudo apt install -y apt-utils 

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Clone TON
      run: |
        git clone --recursive https://github.com/ton-blockchain/ton.git ton
        cd ton; git checkout master; git pull

    - name: Build TON
      run: |
        cd ton
        cp assembly/nix/build-linux-x86-64-nix.sh .
        chmod +x build-linux-x86-64-nix.sh
        ./build-linux-x86-64-nix.sh -t

    - name: Simple binaries test
      run: |
        sudo mv /nix/store /nix/store2
        cd ton
        artifacts/validator-engine -V
        artifacts/lite-client -V
        artifacts/fift -V
        artifacts/func -V

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-portable-22.04-x86-64
        path: ton/artifacts
