name: U-22.04-arm64 (native)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

jobs:
  build:
    runs-on: [self-hosted, ubuntu-22.04-arm64]
    env:
      WORK_DIR: ${{ github.run_id }}-${{ github.run_attempt }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: ./${{ env.WORK_DIR }}

    - run: |
        sudo apt update
        sudo apt install -y apt-utils build-essential git cmake ninja-build libjemalloc-dev

    - name: Install Clang 16
      working-directory: ${{ env.WORK_DIR }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16 all

    - name: Clone TON
      working-directory: ${{ env.WORK_DIR }}
      run: |
        git clone --recursive https://github.com/ton-blockchain/ton.git ton
        cd ton; git checkout ${{ inputs.branch }}; git submodule sync --recursive; git submodule update

    - name: Make AppImages
      run: |
        cp assembly/appimage/create-appimages.sh .
        cp assembly/appimage/AppRun .
        cp assembly/appimage/ton.png .
        chmod +x create-appimages.sh
        ./create-appimages.sh
        rm -rf artifacts

    - name: Build TON libs
      run: |
        cp assembly/native/build-ubuntu-portable-libs.sh .
        chmod +x build-ubuntu-portable-libs.sh
        ./build-ubuntu-portable-libs.sh -a
        cp ./artifacts/libtonlibjson.so appimages/artifacts/
        cp ./artifacts/libemulator.so appimages/artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-native-22.04-arm64-${{ inputs.branch }}
        path: ${{ env.WORK_DIR }}/ton/appimages/artifacts
