name: Win-2019-x86-64

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out current repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Clone TON
        run: |
          git clone --recursive https://github.com/ton-blockchain/ton.git ton
          cd ton
          git checkout ${{ inputs.branch }}
          git submodule sync --recursive
          git submodule update

      - name: Build TON
        run: |
          cd ton
          copy assembly\native\build-windows-github-2019.bat .
          copy assembly\native\build-windows-2019.bat .
          build-windows-github-2019.bat Enterprise

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-win-x86-64-${{ inputs.branch }}
          path: ton/artifacts
