name: Mac-12-x86-64 (native)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - run: |
        sudo apt update
        sudo apt install -y apt-utils build-essential git cmake ninja-build libjemalloc-dev

    - name: Install Clang 16
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16 all

    - name: Clone TON
      run: |
        git clone --recursive https://github.com/ton-blockchain/ton.git ton
        cd ton; git checkout ${{ inputs.branch }}; git pull

    - name: Build TON
      run: |
        cd ton
        cp assembly/native/build-ubuntu-portable.sh .
        chmod +x build-ubuntu-portable.sh
        ./build-ubuntu-portable.sh -t -a

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-native-22.04-x86-64-${{ inputs.branch }}
        path: ton/artifacts
