name: Mac-13-x86-64 (nix)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Clone TON
      run: |
        git clone --recursive https://github.com/ton-blockchain/ton.git ton
        cd ton; git checkout ${{ inputs.branch }}; git submodule sync --recursive; git submodule update

    - name: Build TON
      run: |
        cd ton
        cp assembly/nix/build-macos-nix.sh .
        chmod +x build-macos-nix.sh
        ./build-macos-nix.sh

    - name: Simple binaries test
      run: |
        sudo mv /nix/store /nix/store2
        cd ton
        artifacts/validator-engine -V
        artifacts/lite-client -V
        artifacts/fift -V
        artifacts/func -V

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-mac-x86-64-${{ inputs.branch }}
        path: ton/artifacts
