name: Mac-12-x86-64 (shared)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Clone TON
      run: |
        git clone --recursive https://github.com/ton-blockchain/ton.git ton
        cd ton; git checkout ${{ inputs.branch }}; git pull

    - name: Build TON
      run: |
        cd ton
        cp assembly/native/build-macos-shared.sh .
        chmod +x build-macos-shared.sh
        ./build-macos-shared.sh -t -a

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-shared-mac-x86-64-${{ inputs.branch }}
        path: ${{ env.WORK_DIR }}/ton/artifacts
