name: Mac-14-arm64

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
  workflow_call:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'
        type: string

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: brew install
      run: |
        brew install texinfo

    - name: Clone TON
      run: |
        git clone --recursive https://github.com/ton-blockchain/ton.git ton
        cd ton; git checkout ${{ inputs.branch }}; git submodule sync --recursive; git submodule update

    - name: Build TON
      run: |
        cd ton
        cp assembly/native/build-macos-portable.sh .
        chmod +x build-macos-portable.sh
        ./build-macos-portable.sh -a

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-mac-arm64-${{ inputs.branch }}
        path: ton/artifacts
