name: Run all (master,nix)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'TON branch name'
        required: true
        default: 'master'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out current repository
        uses: actions/checkout@v3        
          
  ton-linux-arm64-nix:
    uses: ./.github/workflows/ton-linux-arm64-nix.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}

  ton-linux-x86-64-nix:
    uses: ./.github/workflows/ton-linux-x86-64-nix.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}

  ton-macos-arm64-nix:
    uses: ./.github/workflows/ton-macos-arm64-nix.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}

  ton-macos-x86-64-nix:
    uses: ./.github/workflows/ton-macos-x86-64-nix.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}

  ton-windows-x86-64:
    uses: ./.github/workflows/ton-windows-x86-64.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
